name: Deploy productive version

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Remove older app version
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PKEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          mkdir -p ~/amarqz-dev
          rm -rf ~/amarqz-dev/*

    - name: Copy application code to the server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PKEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./"
        target: "~/amarqz-dev/"

    - name: SSH into Server, Build Docker Image, and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PKEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/amarqz-dev
          docker build -t amarqz-dev:latest .

          docker stop amarqz_dev || true
          docker rm amarqz_dev || true

          docker run -d --name amarqz_dev --network external --restart unless-stopped amarqz-dev:latest
          docker image prune -f
